# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf913eea388dbc45efa61508f55528ce4f4d33773bb272b6e5f4a1a276fa03f624e31032fd312f551a8922d5d2e70a45719fcc60a6e92e77a5ee1268142582fa

test:
  secret_key_base: 32437e7d76c5f7e377448f893b1603e17c6859bda528fe8cd0a1f41b29e8da59264e940291b742c61696ef45b9690a3dc2a9ba0bef23167a4da5692ed405e7d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
